version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
      - 'postgres-data:/var/lib/postgresql/data'

volumes:
  postgres-data:
